apiVersion: v1
kind: Service
metadata:
  name: srm-frontend
  namespace: srm-credit-engine
  labels:
    app: srm-frontend
spec:
  type: ClusterIP
  selector:
    app: srm-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
